# See https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
sudo: required
dist: trusty

env:
  global:
    - secure: "XAhJXuXqnGlZlU2pGcIQKJ2rF44gIReA0arHwapFII/gR1h+2e6hgqnMXwrZaQa/EvNBaXq7nF3XcTBjrbK+ABeKA/0lOh/7ryIotP0i1YVrca69pSK9BY+Kr1y7ncLMqvoyjBziobOeVZmxbK4RflgUTIO7MKzzb5pNb9SnOK8="
    - secure: "UwH3B4k5Nqt2THYYTY7uRxTPaJXZbK1hHrVsyJjZp/H2uFTYtQTxXpNb9aR7wuHuhLjXwKkq3gEXxEqhfy6V8+ZPbee6MUNvoYe/HhaPjsmTzcVihTBbO9e7g0bIQFc9bzwY15Y1ImshLcDAYvaXwXapy4Z/KadLiBheyqMk8Cs="
    # Scaladocs
    - secure: "FPfJbtXmhyMTh/eh9B/f6JZIv6aw+XZMipYlJsdgMEv+XKzL1tdYbKQv8G4C13lhyBZmOlQAbOhl4mRUBmq0FqG3361Y9SS4o5KfDRkZNErBTb8tveoRgKLkdLPwooAOUmRUeygKmhO4ehdQsMXCZmCk33nDq/ZrNallfnCRdm8="

language: scala

scala:
  - "2.11.12"

addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: localhost

jdk:
  - openjdk8
  - oraclejdk8

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash .travis/decrypt-keys.sh; fi
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt "project core" test
  - sbt "project example" test

notifications:
  email:
    recipients:
      - nzimmerman@azavea.com
      - echeipesh@azavea.com
  slack:
    secure: "RPNymWgr5RXN2LpDERitGAP7pckR19znqAlrcuKE46O7saqlenX6ii8ToRHOe1ba0udJO0B1n2R2OzTlw14AkuETyRKX4X8OtVlU/dtfTHfVMbX6+oRPd1g1mfLrLavR5o2ml/KoIvi9QLbNcVHfqoeA+xxW5TJTm9zayRC9d1M="

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash .travis/publishMicrosite.sh; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping deploy and release"; fi

