version: '3'
services:
  overlay-example:
    image: quay.io/geotrellis/server:latest
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
    build:
      context: docker
      dockerfile: overlay.dockerfile
  persistence-example:
    image: quay.io/geotrellis/server:latest
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
    build:
      context: docker
      dockerfile: persistence.dockerfile
  ndvi-example:
    image: quay.io/geotrellis/server:latest
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
    build:
      context: docker
      dockerfile: ndvi.dockerfile

