version: '3'
services:
  overlay-example:
    image: quay.io/geotrellis/server:latest
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
    build:
      context: docker
      dockerfile: overlay.dockerfile
  persistence-example:
    image: quay.io/geotrellis/server:latest
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
    build:
      context: docker
      dockerfile: persistence.dockerfile
  ndvi-example:
    image: quay.io/geotrellis/server:latest
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
    build:
      context: docker
      dockerfile: ndvi.dockerfile

  server-microsite:
    image: quay.io/geotrellis/server-microsite:latest
    command: bash -c "cd /root/geotrellis-server/docs/target/site && jekyll serve --host 0.0.0.0"
    ports:
      - "4000:4000"
    volumes:
      - $HOME/.sbt:/root/.sbt
      - $HOME/.ivy2:/root/.ivy2
      - ./:/root/geotrellis-server
    build:
      context: docker
      dockerfile: microsite.dockerfile
