version: '3'
services:
  geotrellis-overlay:
    image: quay.io/geotrellis/server:latest
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
    build:
      context: docker
      dockerfile: overlay.dockerfile
